name: build-docker-ecr

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      context:
        type: string
        required: false
        default: .
      region:
        type: string
        required: true
    secrets:
      ecr_access_key:
        required: true
      ecr_secret_key:
        required: true
      build_secrets:
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: config-environment
        env:
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          number: ${{ github.run_number }}
          name  : ${{ inputs.name }}
        run: |
          echo "branch=${branch//\//-}"           >> $GITHUB_ENV
          echo "commit=${commit:0:7}"             >> $GITHUB_ENV
          echo "number=${number}"                 >> $GITHUB_ENV
          echo "name=${name}"                     >> $GITHUB_ENV

      - name: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: config-aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ecr_access_key }}
          aws-secret-access-key: ${{ secrets.ecr_secret_key }}
          aws-region: ${{ inputs.region }}

      - name: login-ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: docker-build-push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ inputs.context }}
          secrets: ${{ secrets.build_secrets }}
          tags: |
            ${ecr_registry}/${name}:${branch}
            ${ecr_registry}/${name}:${branch}-${commit}
            ${ecr_registry}/${name}:github-${number}
